name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: ALMGitHUB
      solution_exported_folder:
        description: 'Folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: 'https://org31cddccd.api.crm4.dynamics.com'
  CLIENT_ID: '1af267f9-3dd0-4cec-8f94-574a5ae46f4a'
  TENANT_ID: 'fd799da1-bfc1-4234-a91c-72b3a1cb9e26'

jobs:
  export-from-dev:
    runs-on: windows-latest

    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Export solution (unmanaged)
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

    - name: Export solution (managed)
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        managed: true
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}_managed.zip

    - name: Unpack solution
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
        solution-type: 'Both'
        overwrite-files: true

    - name: Branch solution and prepare for Pull Request
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder }}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.PAT_TOKEN }}
        allow-empty-commit: true

    - name: Debug - List files
      run: |
        echo "Listing files in exported folder:"
        ls ${{ github.event.inputs.solution_exported_folder }}
        echo "Listing files in solution folder:"
        ls ${{ github.event.inputs.solution_folder }}
        echo "Listing files in target folder:"
        ls ${{ github.event.inputs.solution_target_folder }}
