name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: ALMGitHUB
      # Do not change these values
      solution_exported_folder:
        description: 'Folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Folder name to be created and checked in *do not change*'
        required: true
        default: solutions/

env:
  # Edit your values here
  ENVIRONMENT_URL: 'https://org31cddccd.api.crm4.dynamics.com'
  CLIENT_ID: '1af267f9-3dd0-4cec-8f94-574a5ae46f4a'
  TENANT_ID: 'fd799da1-bfc1-4234-a91c-72b3a1cb9e26'

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    # Or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Who-am-I action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: Export unmanaged solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        solution-type: Unmanaged

    - name: Export managed solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}_managed.zip
        solution-type: Managed

    - name: Unpack unmanaged solution
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}_unmanaged.zip
        solution-folder: ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Branch and commit unmanaged solution
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Commit unmanaged solution
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ${{ github.event.inputs.solution_folder }}/
        git commit -m "Add unmanaged solution ${{ github.event.inputs.solution_name }}"
        git push origin HEAD:main

    - name: Branch and commit managed solution
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Commit managed solution
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}_managed.zip
        git commit -m "Add managed solution ${{ github.event.inputs.solution_name }}"
        git push origin HEAD:main
