name: import-managed-solution-to-uat
# Import the managed solution to UAT environment

on:
  release:
    types:
      - published

env:
  ENVIRONMENT_URL_UAT: 'https://org3d5cdde.api.crm4.dynamics.com'
  CLIENT_ID: '1af267f9-3dd0-4cec-8f94-574a5ae46f4a'
  TENANT_ID: 'fd799da1-bfc1-4234-a91c-72b3a1cb9e26'

permissions:
  contents: write

jobs:
  import-to-uat:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL_UAT }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}

    - name: download-managed-solution
      uses: actions/download-artifact@v2
      with:
        name: solution-artifact
        path: out/downloaded

    - name: import-solution action
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL_UAT }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-input-file: out/downloaded/Managed/ALMGitHUB.zip
